import "./globals.css";

import { Poppins } from "next/font/google";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "FinSight",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${poppins.className}`}>
          {/* <Header /> */}
          <Header />

          <main className="min-h-screen">{children}</main>

          <Toaster richColors position="top-center" />
          {/* <Footer /> */}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
